import type { WasmExports } from './types';

// WASM binaries will be inlined as base64 by the rollup plugin
// @ts-ignore - resolved at build time
import coreWasmBase64 from '../../wasm/core.wasm?base64';
// @ts-ignore - resolved at build time
import simdWasmBase64 from '../../wasm/simd.wasm?base64';

let wasmInstance: WasmExports | null = null;
let simdSupported: boolean | null = null;
let compileTime = 0;
let instantiateTime = 0;

// Boundary callback counter
let boundaryCallCount = 0;

/**
 * Detect WASM SIMD support
 */
export function detectSimd(): boolean {
  if (simdSupported !== null) return simdSupported;

  try {
    // Test SIMD by attempting to compile a minimal SIMD module
    const simdTest = new Uint8Array([
      0x00,
      0x61,
      0x73,
      0x6d, // WASM magic
      0x01,
      0x00,
      0x00,
      0x00, // Version 1
      0x01,
      0x05,
      0x01,
      0x60,
      0x00,
      0x01,
      0x7b, // Type section: () -> v128
      0x03,
      0x02,
      0x01,
      0x00, // Function section
      0x0a,
      0x16,
      0x01,
      0x14,
      0x00, // Code section
      0xfd,
      0x0c, // v128.const
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x00,
      0x0b, // end
    ]);
    new WebAssembly.Module(simdTest);
    simdSupported = true;
  } catch {
    simdSupported = false;
  }

  return simdSupported;
}

/**
 * Decode base64 to Uint8Array
 */
function base64ToBytes(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

/**
 * Load and instantiate WASM module
 */
export async function loadWasm(): Promise<WasmExports> {
  if (wasmInstance) return wasmInstance;

  const useSimd = detectSimd();
  const wasmBase64 = useSimd ? simdWasmBase64 : coreWasmBase64;
  const wasmBytes = base64ToBytes(wasmBase64);

  // Time compilation
  const compileStart = performance.now();
  const module = await WebAssembly.compile(wasmBytes as BufferSource);
  compileTime = performance.now() - compileStart;

  // Time instantiation with imports
  // The wbg namespace and mangled names are generated by wasm-bindgen
  const instantiateStart = performance.now();
  const instance = await WebAssembly.instantiate(module, {
    wbg: {
      __wbg_boundaryCallback_3bc688e9be4df0fa: () => {
        boundaryCallCount++;
      },
    },
  });
  instantiateTime = performance.now() - instantiateStart;

  wasmInstance = instance.exports as unknown as WasmExports;
  return wasmInstance;
}

/**
 * Get compile/instantiate timing
 */
export function getLoadTiming(): {
  compileTime: number;
  instantiateTime: number;
} {
  return { compileTime, instantiateTime };
}

/**
 * Check if WASM is already loaded
 */
export function isLoaded(): boolean {
  return wasmInstance !== null;
}

/**
 * Get the WASM instance (throws if not loaded)
 */
export function getWasm(): WasmExports {
  if (!wasmInstance) {
    throw new Error('WASM not loaded. Call loadWasm() first.');
  }
  return wasmInstance;
}

/**
 * Reset boundary call counter
 */
export function resetBoundaryCounter(): void {
  boundaryCallCount = 0;
}

/**
 * Get boundary call count
 */
export function getBoundaryCount(): number {
  return boundaryCallCount;
}

/**
 * Get the raw WASM bytes (for worker use)
 */
export function getWasmBytes(): Uint8Array {
  return base64ToBytes(coreWasmBase64);
}
